"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const fs=require("node:fs");
const {IXI_FINANCIAL_ACTIONS,getEffectiveFinancialPermissions}=require("./IXIFinancialPermissionEngine");
const {createPaymentDocument}=require("./IXIFinancialPaymentFactory");
const {createCostCreditDocument}=require("./IXIFinancialCreditFactory");
const {createPayablesControlDocument}=require("./IXIFinancialPayablesControlFactory");
const {validateFinancialDocument}=require("./IXIFinancialValidationBridge");
const providerService=require("./IXIFinancialProviderService");
const {assertPayablesSettlementAvailable}=require("./IXIFinancialCommandEngine");

test("accounting authority includes segregated A/P settlement capabilities",()=>{const permissions=getEffectiveFinancialPermissions({roles:["financial-accounting"]});assert.ok(permissions.includes(IXI_FINANCIAL_ACTIONS.RECORD_PAYMENT));assert.ok(permissions.includes(IXI_FINANCIAL_ACTIONS.APPLY_VENDOR_CREDIT));assert.ok(permissions.includes(IXI_FINANCIAL_ACTIONS.MANAGE_PAYABLES))});
test("linked outgoing payments require transaction evidence",()=>{const document=createPaymentDocument({financialDocumentId:"ifd_payment001",paymentDirection:"outflow",amount:25,sourceFinancialDocumentId:"ifd_bill001"});assert.equal(validateFinancialDocument(document).ok,false);document.transactionReference="ACH-1";assert.equal(validateFinancialDocument(document).ok,true)});
test("linked vendor credits require a reason code",()=>{const document=createCostCreditDocument({financialDocumentId:"ifd_credit001",amount:25,sourceFinancialDocumentId:"ifd_bill001"});assert.equal(validateFinancialDocument(document).ok,false);document.reasonCode="vendor-credit";assert.equal(validateFinancialDocument(document).ok,true)});
test("A/P control is canonical, Bill-linked, and non-economic",()=>{const document=createPayablesControlDocument({financialDocumentId:"ifd_apcontrol001",sourceFinancialDocumentId:"ifd_bill001",entityPassportId:"pass_entity",actorPassportId:"pass_actor",payablesControl:{payable:{billId:"ifd_bill001",billNumber:"INV-1"}},references:[{role:"entity",passportId:"pass_entity"}]});assert.equal(validateFinancialDocument(document).ok,true);assert.equal(document.accountingTreatment.economicEvent,false);assert.equal(document.lines.length,0)});
test("HTTP command boundary selects settlement-specific authority and trusted identity",()=>{const source=fs.readFileSync(require.resolve("./IXIFinancialCommandRoutes"),"utf8");assert.match(source,/type==="payment".*RECORD_PAYMENT/u);assert.match(source,/type==="credit".*APPLY_VENDOR_CREDIT/u);assert.match(source,/payerPassportId:clean\(accessContext\.entityPassportId\)/u);assert.match(source,/recordedByPassportId:clean\(accessContext\.actorPassportId\)/u)});
test("server settlement control rejects payment above canonical Bill balance",async()=>{const get=providerService.getDocument,list=providerService.listDocumentsByPassport;providerService.getDocument=async()=>({ok:true,data:{record:{financialDocument:{financialDocumentId:"ifd_bill001",documentType:"bill",financialState:"billed",totals:{total:100},billRecord:{context:{entityPassportId:"pass_entity"},approval:{status:"approved"}}}}}});providerService.listDocumentsByPassport=async()=>({ok:true,data:{documents:[{financialDocument:{documentType:"payment",financialState:"paid",paymentDirection:"outflow",sourceFinancialDocumentId:"ifd_bill001",totals:{total:80}}}]}});try{await assert.rejects(()=>assertPayablesSettlementAvailable({entityPassportId:"pass_entity",financialDocument:{documentType:"payment",paymentDirection:"outflow",sourceFinancialDocumentId:"ifd_bill001",totals:{total:25}}}),/exceeds the canonical open Bill balance/u)}finally{providerService.getDocument=get;providerService.listDocumentsByPassport=list}});
