"use strict";

const {
  clean,
  safeArray
} = require("../util");

function section(
  title,
  body
) {
  const value =
    clean(body);

  if (!value) {
    return "";
  }

  return `## ${title}\n\n${value}\n`;
}

function buildTicketIssueTitle(
  ticket
) {
  const prefix =
    clean(
      ticket.displayNumber
    ) || "IXI TICKET";

  const title =
    clean(
      ticket.headline
    ) ||
    clean(
      ticket.originalRequest
    ).slice(0, 100) ||
    "Engineering work";

  return `[${prefix}] ${title}`;
}

function buildTicketIssueBody(
  ticket
) {
  const edits =
    safeArray(
      ticket.editSections
    )
      .filter(
        item =>
          clean(
            item.description
          )
      )
      .map(
        (item, index) =>
          `### EDIT ${String(index + 1).padStart(2, "0")}\n\n${clean(item.description)}`
      )
      .join("\n\n");

  const context =
    [
      ["Route", ticket.context?.route],
      ["Environment", ticket.context?.environment],
      ["Object ID", ticket.context?.objectId],
      ["Passport ID", ticket.context?.passportId],
      ["Card Family", ticket.context?.cardFamily],
      ["Card Context", ticket.context?.cardContext],
      ["Face", ticket.context?.face],
      ["Scale", ticket.context?.scaleMode],
      ["TRAN$ACT Module", ticket.context?.transactModule]
    ]
      .filter(([, value]) => clean(value))
      .map(
        ([key, value]) =>
          `- **${key}:** ${clean(value)}`
      )
      .join("\n");

  return [
    `<!-- IXI-TICKET:${clean(ticket.ticketId)} -->`,
    `**IXI Ticket:** ${clean(ticket.displayNumber)}`,
    `**Ticket ID:** \`${clean(ticket.ticketId)}\``,
    `**Source:** ${clean(ticket.source)}`,
    `**Type:** ${clean(ticket.type)}`,
    `**Priority:** ${clean(ticket.priority)}`,
    `**Execution:** ${clean(ticket.executionClass)}`,
    `**Repository:** ${clean(ticket.repository)}`,
    "",
    section(
      "ORIGINAL REQUEST",
      ticket.originalRequest
    ),
    section(
      "REQUESTED EDITS",
      edits
    ),
    section(
      "CAPTURED CONTEXT",
      context
    ),
    "---",
    "_Generated by IXI Ticket Engine. Captured context is diagnostic evidence only and does not establish authority._"
  ]
    .filter(Boolean)
    .join("\n");
}

module.exports = {
  buildTicketIssueTitle,
  buildTicketIssueBody
};
